version: "3.9"

services:
  sparsh-app:
    container_name: sparsh-app
    image: sparsh-app:latest
    build:
      context: ./app
    command: npm start
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
    networks:
      sparsh-network:
        aliases:
          - app

  infra:
    container_name: app-infra
    image: app-infra:latest
    build:
      context: ./infra
    networks:
      sparsh-network:
        aliases:
          - app-infra
